//To be posted unminified soon, the code needs cleanup and refactoring
function birdsongMobile(){function l(){}function m(b,c){for(var e=[];b;b=b.nextSibling)1==b.nodeType&&b!=c&&e.push(b);return e}var j=new Date,f=this;this.DOMLoad=[];this.domLoaded=this.contentLoaded=!1;this.agent=navigator.userAgent.toLowerCase();f.OnDomReady=function(b){f.domLoaded?b.call(this):f.DOMLoad.push(b)};this.fs=new function(b){var c=b.agent;try{if(document.createEvent("TouchEvent"),"ontouchstart"in document.documentElement||document.createEvent("TouchEventasdf1234"),b.onmousedown="ontouchstart",
b.onmouseup="ontouchend",b.onmousemove="ontouchmove",b.touches=!0,b.getPageX=function(b){return b.touches[0].pageX},b.getPageY=function(b){return b.touches[0].pageY},b.contentLoaded=!0,document.getElementsByTagName("html")[0].id="no-hover",window.opera)b.browser="opera",b.prefix="o",b.contentLoaded=!1;else if(0<=c.indexOf("Mac OS"))b.browser="ios",b.prefix="webkit";else if(0<=c.indexOf("ndroid")){b.browser="Android";if(0<=c.indexOf("webkit")){b.prefix="webkit";var e=parseFloat(c.substr(c.indexOf("ndroid")+
6).substr(1,c.indexOf(";")));2.3>e&&(document.getElementsByTagName("html")[0].className="no3d")}setTimeout(function(){window.scrollTo(0,1)},62)}else 0<=c.indexOf("series60")||0<=c.indexOf("symbian")?(b.browser="symbian",b.prefix="webkit"):0<=c.indexOf("blackberry")?(b.browser="blackberry",b.prefix=""):document.all?(b.browser="ie",b.prefix="ms"):0<=c.indexOf("palm")?(b.browser="palmOS",b.prefix=""):0<=c.indexOf("webkit")?(b.browser="webkit",b.prefix="webkit"):0<=c.indexOf("gecko")?(b.browser="moz",
b.prefix="Moz"):(b.browser="undefined",b.prefix="")}catch(d){b.onmousedown="onmousedown",b.onmouseup="onmouseup",b.onmousemove="onmousemove",b.touches=!1,b.getPageX=function(b){return b.clientX},b.getPageY=function(b){return b.clientY},window.opera?(b.browser="opera",b.prefix="o",b.contentLoaded=!1,0<=c.indexOf("mini")&&(document.getElementsByTagName("html")[0].className="opMini",j-=150,b.DOMLoad.push(function(){var b=document.body.clientWidth;280<=b&&480>b&&(document.getElementsByTagName("body")[0].style.width=
b+"px")}))):!document.addEventListener&&0<=c.indexOf("msie")?(b.browser="ie",b.prefix="ms",b.contentLoaded=!1,0<=c.indexOf("mobile")?(document.getElementsByTagName("html")[0].className="ie",e=parseFloat(c.substr(c.indexOf("msie")+5).substr(0,3)),7>=e&&(j-=200)):(document.getElementsByTagName("html")[0].className="ie",e=parseFloat(c.substr(c.indexOf("msie")+5).substr(0,3)),7>=e&&(document.getElementsByTagName("html")[0].className="ie deskIE7"))):0<=c.indexOf("MSIE")?(b.browser="ie",b.prefix="ms"):
0<=c.indexOf("series60")||0<=c.indexOf("symbian")?(b.browser="symbian",b.prefix="webkit",b.contentLoaded=!1):0<=c.indexOf("blackberry")?(b.browser="blackberry",b.prefix="",b.contentLoaded=!1):0<=c.indexOf("palm")?(b.browser="palmOS",b.prefix="",b.contentLoaded=!1):0<=c.indexOf("webkit")?(b.browser="webkit",b.prefix="webkit",b.contentLoaded=!0):0<=c.indexOf("gecko")?(b.browser="moz",b.prefix="Moz",b.contentLoaded=!0):(b.browser="undefined",b.prefix="",b.contentLoaded=!1)}b.cssTransitions=!1;c=document.createElement("div");
c.innerHTML=1<=b.prefix.length?'<div style= "-'+b.prefix.toLowerCase()+'-transition:color 1s linear;"></div>':'<div style= "transition:color 1s linear;"></div>';b.cssTransitions=void 0!==c.firstChild.style[b.prefix+"Transition"]}(f);this.onHandler={addHandler:function(b,c,e){var d=c[b];c[b]=null!=d?function(b){d(b);e(b)}:function(c){b=b||window.event;e(c)}},killHandler:function(b,c){c[b]=null}};if(f.touches){var p=function(b){f.stopPropagation(b);var c=b.currentTarget,e=b.touches[0];if(f.contextTimeout){var d=
f.sos2.className;0<=d.indexOf("clic")&&(f.sos2.className=d.substr(0,d.indexOf("clic")))}c.className+=" clicked";f.sos=b.srcElement;f.sos2=c;f.srx=e.pageX;f.sry=e.pageY;f.newx=f.srx;f.newy=f.sry;f.contextTimeout=setTimeout(function(){var b=f.sos2.className;0<=b.indexOf("clic")&&(f.sos2.className=b.substr(0,b.indexOf("clic")));f.contextTimeout=!1},1520);return!1};l.prototype.touchS_NoBlock=function(b){if(1<b.touches.length)return f.preventDefault(b),f.stopPropagation(b),!1;var c=f.hObj;p(b);c.addEventObserver(b.currentTarget,
c,"touchmove","touchM");c.addEventObserver(b.currentTarget,c,"touchend","touchE");return!1};l.prototype.touchS=function(b){f.preventDefault(b);if(1<b.touches.length)return f.stopPropagation(b),!1;var c=f.hObj;p(b);c.addEventObserver(b.currentTarget,c,"touchmove","touchM");c.addEventObserver(b.currentTarget,c,"touchend","touchEClick");return!1};l.prototype.touchM=function(b){b=b.touches[0];f.newx=b.pageX;f.newy=b.pageY};var q=function(b,c,e,d){c=f.hObj;f.stopPropagation(b);c.removeEventObserver(b.currentTarget,
c,"touchmove","touchM");c.removeEventObserver(b.currentTarget,c,"touchend",e);clearTimeout(f.contextTimeout);f.contextTimeout=!1;""!=(b=f.sos2.className)?f.sos2.className=b.substr(0,b.indexOf("clic")):(b=f.sos2.parentNode.className,f.sos2.parentNode.className=b.substr(0,b.indexOf("clic")));f.newx<f.srx+40&&f.newx>f.srx-40&&f.newy<f.sry+10&&f.newy>f.sry-10&&(b=document.createEvent("MouseEvents"),b.initEvent(d,!0,!0),f.sos.dispatchEvent(b));return!1};l.prototype.touchE=function(b,c){q(b,c,"touchE",
"vnt");return!1};l.prototype.touchEClick=function(b,c){q(b,c,"touchEClick","click");return!1}}l.prototype.addEventObserver=function(b,c,e,d){var f=d+"_"+e;c[f]=function(e){c[d](e,b)};b.addEventListener(e,c[f],!1)};l.prototype.removeEventObserver=function(b,c,e,d){d=d+"_"+e;b.removeEventListener(e,c[d],!1);delete c[d]};this._obj={$:function(b){this.el=b;return this},toggleClass:function(b){var c=this.el,e=c.className,d;c.className=0<=(d=e.indexOf(b))?e===b?"":e.substr(0,d-1)+e.substr(d+b.length):!e||
""===e?b:c.className+(" "+b);return this},prev:function(){for(var b=this.el.previousSibling;b&&3===b.nodeType;)b=b.previousSibling;this.el=b;return this},next:function(){for(var b=el.nextSibling;b&&3===b.nodeType;)b=b.nextSibling;this.el=b;return this},index:function(){for(var b=0,c=this.el.previousSibling;c;)3!==c.nodeType&&b++,c=c.previousSibling;return b},parent:function(){this.el=this.el.parentNode;return this},parents:function(b,c){var e=this.el,d,i,g=i=0,k;c||(c=1);0===b?(d=function(){return!0},
k=-1):(k=b.indexOf("."),-1===k?(d=function(b,c){return f.tagCheck(b,c)},g=b):0===k?(d=function(b,c,d){return f.classCheck(b,d)},i=b.substr(1)):(d=function(b,c,d){return f.tagCheck(b,c)&&f.classCheck(b,d)},g=b.substr(0,k),i=b.substr(k+1)));for(;0<c--;)e=e.parentNode;for(;;){if(d(e,g,i))return delete this.callback,this.el=e,this;e=e.parentNode}},children:function(){return m(this.el.childNodes[0],null)},findUpwards:function(b){var b=f.strtok(b),c;if(0<(c=b.indexOf("."))){var e=b.substr(0,c),b=b.substr(c+
1),d=this.el;if(0===e.length)for(;;){c=d.childNodes;for(var i=0,g=c.length;i<g;i++)if(0<=c[i].className.indexOf(b))return delete this.el,f.qEL(c[i]);d=d.parentNode}else for(;;){c=d.getElementsByTagName(e);i=0;for(g=c.length;i<g;i++)if(0<=c[i].className.indexOf(b))return delete this.el,f.qEL(c[i]);d=d.parentNode}}else for(;;)if(d=d.parentNode,d.tagName==e)return delete this.el,f.qEL(d)},closestUpwards:function(b){var b=f.strtok(b),c;if(0<(c=b.indexOf("."))){var e=b.substr(0,c),d=b.substr(c+1),i=this.el;
if(0==e.length)for(;;){var b=this.index(),g=[],i=i.parentNode;c=i.childNodes;for(var k=0,n=c.length;k<n;k++)0<=c[k].className.indexOf(d)&&g.push(k);if(0<g.length){e=100;k=i=0;for(n=g.length;k<n;k++)d=f.qEL(c[g[k]]).index(),Math.abs(d-b)<e&&(e=Math.abs(d-b),i=g[k]);return f.qEL(c[i])}}else for(;;){b=f.qEL(i).index();g=[];i=i.parentNode;c=i.getElementsByTagName(e);k=0;for(n=c.length;k<n;k++)0<=c[k].className.indexOf(d)&&g.push(k);if(0<g.length){e=100;k=i=0;for(n=g.length;k<n;k++)d=f.qEL(c[g[k]]).index(),
Math.abs(d-b)<e&&(e=Math.abs(d-b),i=g[k]);return f.qEL(c[i])}}}else for(;;)if(i=i.parentNode,i.tagName==e)return f.qEL(i)},getLastSiblings:function(){for(var b=this.el,c=b.parentNode.lastChild,e=[];c;c=c.previousSibling)if(1==c.nodeType&&c!=b)e.push(c);else if(c===b)break;return e},curOffsetLeft:function(){var b=0,c=this.el.offsetParent;if(c&&c.offsetParent){do b+=c.offsetLeft;while(c=c.offsetParent)}return b},getOutsideSize:function(b,c){var e=this.el;if(c)return e=window.getComputedStyle(e,null).getPropertyValue(b),
parseInt(e);var d="width"==b?e.offsetWidth:e.offsetHeight;return e=d-(("width"==b?e.offsetWidth:e.offsetHeight)-d)},getSiblings:function(){var b=this.el;return m(b.parentNode.childNodes[0],b)},makeActive:function(b){var c=this.el;if(c){for(var e=this.getSiblings(),d=0,f=e.length;d<f;d++){var g=e[d],k;if(0<=(k=g.className.indexOf(b)))g.className=g.className.substr(0,k-1)}c.className+=" "+b}return this},get:function(){return this.el},CLR:function(){delete this.el;return!1},scroll:function(b){this.Scroller.render(this.el,
b);return this},scrollTo:function(b){this.Scroller.renderINIT(this.el,b);return this},Scroller:{$this:function(){return this},speed:10,currScrollTop:0,focus:!1,gy:function(b){var c=b.offsetTop;if(b.offsetParent)for(;b=b.offsetParent;)c+=b.offsetTop;return c},scrollTop:function(){var b=document.body,c=document.documentElement;return b&&b.scrollTop?b.scrollTop:c&&c.scrollTop?c.scrollTop:window.pageYOffset?window.pageYOffset:0},add:function(b,c,e){if(b.addEventListener)return b.addEventListener(c,e,
!1);if(b.attachEvent)return b.attachEvent("on"+c,e)},end:function(b){"click"==b.type&&(f.stopPropagation(b),f.preventDefault(b))},scroll:function(b){a=h=this.currScrollTop;this.currScrollTop=a=b>a?a+Math.ceil((b-a)/this.speed):a+(b-a)/this.speed;window.scrollTo(0,a);this.currScrollTop=a=parseInt(a);if(a==b||this.offsetTop==a)clearInterval(this.interval),this.focus&&this.focus.focus();this.offsetTop=a},renderINIT:function(b,c){var e=this,d=this.scrollTop(),f=e.gy(b);this.currScrollTop=this.scrollTop();
e.focus=c;clearInterval(e.interval);f<=d||280<f-d?e.interval=setInterval(function(){e.scroll(f)},10):this.focus&&this.focus.focus()},render:function(b,c){var e=this;c||(c=b.hash);c&&-1!=c.indexOf("#")&&(e.add(b,"click",e.end),b.onclick=function(){e.end(this);e.focus=!1;b=c.substr(1);e.currScrollTop=e.scrollTop();var d=document.getElementById(b);clearInterval(e.interval);var f=e.gy(d),d=e.scrollTop();f<=d||300<f-d?e.interval=setInterval(function(){e.scroll(f)},10):e.focus&&e.focus.focus()})}}};this.qEL=
function(b){return Object.create(f._obj).$(b)};this._obj.find=function(b,c){var b=f.strtok(b),e,d=this.el,i=b.length-1;if(b instanceof Array){for(e=0;e<i;e++)d=d.getElementsByTagName(b[e])[0];e=d.getElementsByTagName(b[i])[c];void 0==e&&(e=d.getElementsByTagName(b[i])[c-1])}else e=d.getElementsByTagName(b)[c];d=Object.create(f._obj);return d.$(e)};this.tagCheck=function(b,c){return b.tagName===c.toUpperCase()};this.classCheck=function(b,c){return 0<=b.className.indexOf(c)};Object.create||(Object.create=
function(b){function c(){}c.prototype=b;return new c});window.getComputedStyle||(window.getComputedStyle=function(b){this.el=b;this.getPropertyValue=function(c){var e=/(\-([a-z]){1})/g;"float"==c&&(c="styleFloat");if(!b.currentStyle)return"width"===c?b.offsetWidth:b.offsetHeight;if(e.test(c))c=c.replace(e,function(b,c,e){return e.toUpperCase()});else if("auto"==b.currentStyle[c])return"width"==c?b.offsetWidth:b.offsetHeight;return b.currentStyle[c]?b.currentStyle[c]:null};return this},Array.prototype.indexOf||
(Array.prototype.indexOf=function(b,c){null==c?c=0:0>c&&(c=Math.max(0,this.length+c));for(var e=c,d=this.length;e<d;e++)if(this[e]===b)return e;return-1}));this.getElementsByClass=document.getElementsByClassName?function(b,c){return c.getElementsByClassName(b)}:function(b,c){for(var e=[],d=RegExp("\\b"+b+"\\b"),f=c.getElementsByTagName("*"),g=0,k=f.length;g<k;g++)d.test(f[g].className)&&e.push(f[g]);return e};document.addEventListener?(this.stopPropagation=function(b){b.stopPropagation()},this.preventDefault=
function(b){b.preventDefault()}):(this.stopPropagation=function(){window.event.cancelBubble=!0},this.preventDefault=function(){window.event.returnValue=!1});this.keyCounter=function(b,c,e){f.stopPropagation(c);setTimeout(function(){var c=b.value.length;if(c>=e){var i=f.qEL(b).findUpwards("span.num").get();i.getElementsByTagName("span")[0].innerHTML=e;b.value=b.value.substr(0,e);i.className="num red";return!1}i=f.qEL(b).findUpwards("span.num").get();i.className="num";i.getElementsByTagName("span")[0].innerHTML=
c},12)};this.clearVal=function(b){b.getAttribute("alt")==b.value&&(b.value="");b.onblur||(b.onblur=function(){0===this.value.length&&(this.value=this.getAttribute("alt"))})};if(self.innerHeight)var o=function(){return self.innerWidth};else document.documentElement&&document.documentElement.clientHeight?o=function(){return document.documentElement.clientWidth}:document.body&&(o=function(){return document.body.clientWidth});this.orientation=function(b){var c=o();b.className=400<=c?"vrt":"hrz"};this.orientationINIT=
function(){var b;if(void 0!=(b=document.getElementById("content")))this.orientation(b),setInterval(function(){f.orientation(b)},580)};this.EACH=function(b,c){for(var e=0,d=b.length;e<d&&!(!1===c.call(b[e]));e++);};this.strtok=function(b){var c=b.indexOf(" "),e=[];if(0<c){do e.push(b.substr(0,c)),b=b.substr(c);while(0<(c=b.indexOf(" ")));e.push(b.substr(1,b.length))}else e=b;return e};this.extend=function(){var b,c,e,d=arguments[0]||{},f=1,g=arguments.length;"boolean"===typeof d&&(d=arguments[1]||
{},f=2);g===f&&(d=this,--f);for(;f<g;f++)if(null!=(b=arguments[f]))for(c in b)e=b[c],d!==e&&void 0!==e&&(d[c]=e);return d};this.hObj=new l(0,0,0,0);j=new Date-j;this.fx=new function(b){var c=this;this.frameRate=b;this.mInterval={};this.Core=c.frameRate?function(b){var d={obj:null,steps:100,stepVal:1,init:0,property:null,to:100,save:0,callback:function(){},valueType:"px",display:"none",reset:!1},d=f.extend(d,b),i=parseInt(d.steps),g=d.init;d.init>d.to&&(d.stepVal=0<d.stepVal?-1*d.stepVal:d.stepVal);
clearInterval(c.mInterval[d.obj]);g+=d.stepVal;d.obj.style[d.property]=g+d.valueType;i--;c.mInterval[d.obj]=setInterval(function(){g+=d.stepVal;d.obj.style[d.property]=g+d.valueType;i--;0>=i&&(d.obj.style.display=0===d.init?"block":d.display,d.obj.style[d.property]=d.reset?d.to+d.valueType:"",clearInterval(c.mInterval[d.obj]),c.mInterval[d.obj]=null,d.callback())},c.frameRate)}:function(b){var d={obj:null,steps:100,stepVal:1,init:0,property:null,to:100,save:0,callback:function(){},valueType:"px",
display:"none",reset:!0},d=f.extend(d,b);d.obj.style.display=0===d.init?"block":d.display;d.obj.style[d.property]=d.reset?d.to+d.valueType:"";clearInterval(c.mInterval[d.obj]);c.mInterval[d.obj]=null;d.callback()};this.toggleSlide=f.cssTransitions?function(b,d,i,g,k){var n=b.style,l=b.parentNode,j=l.className;if(0<j.indexOf("closed")){l.className=j.substr(0,j.indexOf("closed")-1);n.display="block";var m=f.qEL(b).getOutsideSize(g);n[g]=i+"px";n[f.prefix+"Transition"]="";setTimeout(function(){n[f.prefix+
"Transition"]=g+" "+d+"ms ease-in-out";n[g]=m+"px";c.mInterval[b]=setTimeout(function(){n[g]=m;clearTimeout(c.mInterval[b]);c.mInterval[b]=null;k()},d+20)},16)}else if(null===c.mInterval[b]){var o=f.qEL(b).getOutsideSize(g)+"px";n.webkitTransition="";n[g]="";m=f.qEL(b).getOutsideSize(g)+"px";n[g]=o;setTimeout(function(){n.webkitTransition=g+" "+d+"ms ease-in-out";n[g]=i+"px";c.mInterval[b]=setTimeout(function(){n[g]=m;clearTimeout(c.mInterval[b]);c.mInterval[b]=null;n.display="none";l.className=j+
" closed";k()},d+20)},14)}}:function(b,d,i,g,k){var l=b.parentNode,j=l.className,m=b.style;if(0<j.indexOf("closed"))if(l.className=j.substr(0,j.indexOf("closed")-1),b.style.display="block",j=f.qEL(b).getOutsideSize(g),m[g]="0px",c.frameRate){var d=d/c.frameRate,o,r=(i+j)/d;m[g]="0px";d--;c.Core({obj:b,steps:d,stepVal:r,init:0,property:g,to:i,save:j,callback:k})}else m[g]="",k();else c.frameRate?(d/=c.frameRate,null==c.mInterval[b]&&(j=f.qEL(b).getOutsideSize(g),r=(i-j)/d,o=j+r,m[g]=o+" px",d--,c.Core({obj:b,
steps:d,stepVal:r,init:o,property:g,to:i,save:j,callback:function(){k();l.className+=" closed"}}))):(j=f.qEL(b).getOutsideSize(g),m.display="none",m[g]="",l.className+=" closed",k())}}(10>j?13:18>j?14:25>j?18:33>j?26:!1);if(this.contentLoaded)document.addEventListener("DOMContentLoaded",function(){document.removeEventListener("DOMContentLoaded",arguments.callee,!1);f.DocumentReady()},!1);else if(document.readyState)var r=setInterval(function(){"complete"==document.readyState&&(clearInterval(r),f.DocumentReady())},
6);else window.onload=f.DocumentReady();f.DocumentReady=function(){this.domLoaded=!0;this.orientationINIT();if(this.touches){for(var b=document.getElementById("body").getElementsByTagName("a"),c=0,e=b.length;c<e;++c)b[c].addEventListener("touchstart",this.hObj.touchS_NoBlock,!1);this.EACH(b,function(){var b=this;null==b.onclick?(b.mem=b.href,b.addEventListener("vnt",function(c){c.stopPropagation();window.location.href=b.mem},!1)):(b.addEventListener("click",function(b){b.preventDefault();b.stopPropagation()},
!1),b.mem=b.onclick,b.addEventListener("vnt",function(c){c.stopPropagation();b.mem(this)},!1));b.onclick=function(){return!1}})}else{b=document.getElementById("body").getElementsByTagName("a");c=0;for(e=b.length;c<e;++c)b[c].addEventListener("click",function(b){b.preventDefault()},!1)}"0%"==document.getElementById("volume").innerHTML&&(is_mute=!0);vlcJS.pauseButton=document.getElementById("pauseButton");vlcJS.volume=document.getElementById("volume");e=this.DOMLoad.length;for(c=0;c<e&&!this.DOMLoad[c].call(this);++c);
}}
birdsongMobile.prototype.sliderStart=function(l,m,j){var f=this;j||(j=l.parentNode);if(1===j){var j=l,l=l.childNodes[0],p=this.qEL(j).getOutsideSize("width",!0),q=this.qEL(l).curOffsetLeft(),o=parseInt(parseFloat(l.style.left)/100*p);o||(o=0);m=this.getPageX(m)-q;o=0>m?0:Math.min(m,p);l.style.left=100*(o/p)+"%"}else p=this.qEL(j).getOutsideSize("width",!0),q=this.qEL(l).curOffsetLeft(),(o=parseInt(parseFloat(l.style.left)/100*p))||(o=0);this.onHandler.addHandler(this.onmousedown,document,function(l){f.preventDefault(l)});this.onHandler.addHandler(this.onmousemove,
document,function(j){j||(j=window.event);var b=f.getPageX(j)-q-16,c=p-18;-20<=o&&o<=c&&(o=0>b?0:Math.min(b,c),l.style.left=100*(o/p)+"%");f.preventDefault(j);f.stopPropagation(j);vlcJS.slider_seek(j,this.parentNode)});f.onHandler.addHandler(f.onmouseup,document,function(j){f.onHandler.killHandler(f.onmousemove,document);f.onHandler.killHandler(f.onmousedown,document);f.onHandler.killHandler(f.onmouseup,document);f.stopPropagation(j);f.preventDefault(j);vlcJS.slider_seek(j,this.parentNode);return!1});
return!1};var birdsong=new birdsongMobile;birdsong.OnDomReady(function(){if(this.touches)for(var l=this.getElementsByClass("scrub",document.getElementById("one")),m=0,j=l.length;m<j;++m){l[m].ontouchstart=l[m].onmousedown;l[m].onmousedown=null;var f=l[m].parentNode;f.ontouchstart=f.onmousedown;f.onmousedown=null}});